server:
  port: 3001
  servlet:
    context-path: /quiz-app-service

spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/webquiz
      username: postgres
      password: Aditya623880
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

bezkoder:
  app:
    jwtSecret: "======================BezKoder=Spring==========================="
    jwtExpirationMs: 86400000
